### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by Vacreio** [Incredibleflamer/anime-batch-downloader#2]
![Screenshot 2023-12-25 090942](https://github.com/Incredibleflamer/anime-batch-downloader/assets/154751694/45462785-6c46-4e1c-9126-12921de073f8)

Im getting this error and im stupid so I have no idea what to do

**Comment by Incredibleflamer** [comment]
i updated the code right now download and this error is caused cuz you havent change the download location,

open : downloadlocation.json
in that paste where you wanna download your anime. 

if you dont get it watch the video below 

https://private-user-images.githubusercontent.com/84078595/206552277-618b6038-1f5e-43fa-bda6-8a78c096e0d0.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MDU5OTYsIm5iZiI6MTcwMzYwNTY5NiwicGF0aCI6Ii84NDA3ODU5NS8yMDY1NTIyNzctNjE4YjYwMzgtMWY1ZS00M2ZhLWJkYTYtOGE3OGMwOTZlMGQwLm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDE1NDgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyYzAxNDlhZDM0ODBhMDNmODE4NTY1NzZkYjExYjg2M2RlYzhiMmUyMWFjZDk1YmY3YzkyMzE0Njg4MDhmYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LRC94cNX68_X1Y4B8ycNO-MVLKUlmo2XP-CuY_5fF3Y

**Comment by Vacreio** [comment]
![image](https://github.com/Incredibleflamer/anime-batch-downloader/assets/154751694/b7dc4c70-0a5b-46e6-a9e8-7e3009fa5896)
![image](https://github.com/Incredibleflamer/anime-batch-downloader/assets/154751694/fc0a77b1-e84d-45f6-a1fa-1c5fabb4bd4f)
Im still getting that error. I have def updated the download location?

**Comment by Vacreio** [comment]
Okay, so I changed the \s to/s like in the video, and it moved on, asked for which Naruto I wanted to download, I selected option 1, and then I got this long error:
 ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in _run_module_as_main:198                                                                       │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │   alter_argv = False                                                                         │ │
│ │         code = <code object <module> at 0x000002210FA45730, file                             │ │
│ │                "C:\Users\sunan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_… │ │
│ │                line 1>                                                                       │ │
│ │ main_globals = {                                                                             │ │
│ │                │   '__name__': '__main__',                                                   │ │
│ │                │   '__doc__': None,                                                          │ │
│ │                │   '__package__': '',                                                        │ │
│ │                │   '__loader__': <zipimporter object                                         │ │
│ │                "C:\Users\sunan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_… │ │
│ │                │   '__spec__': ModuleSpec(name='__main__', loader=<zipimporter object        │ │
│ │                "C:\Users\sunan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_… │ │
│ │                origin='C:\\Users\\sunan\\AppData\\Local\\Packages\\PythonSoftwareFoundation… │ │
│ │                │   '__annotations__': {},                                                    │ │
│ │                │   '__builtins__': <module 'builtins' (built-in)>,                           │ │
│ │                │   '__file__':                                                               │ │
│ │                'C:\\Users\\sunan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python… │ │
│ │                │   '__cached__':                                                             │ │
│ │                'C:\\Users\\sunan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python… │ │
│ │                │   're': <module 're' from 'C:\\Program                                      │ │
│ │                Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qb… │ │
│ │                │   ... +2                                                                    │ │
│ │                }                                                                             │ │
│ │     mod_name = '__main__'                                                                    │ │
│ │     mod_spec = ModuleSpec(name='__main__', loader=<zipimporter object                        │ │
│ │                "C:\Users\sunan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_… │ │
│ │                origin='C:\\Users\\sunan\\AppData\\Local\\Packages\\PythonSoftwareFoundation… │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│ in _run_code:88                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │       cached = 'C:\\Users\\sunan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python… │ │
│ │         code = <code object <module> at 0x000002210FA45730, file                             │ │
│ │                "C:\Users\sunan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_… │ │
│ │                line 1>                                                                       │ │
│ │        fname = 'C:\\Users\\sunan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python… │ │
│ │ init_globals = None                                                                          │ │
│ │       loader = <zipimporter object                                                           │ │
│ │                "C:\Users\sunan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_… │ │
│ │     mod_name = '__main__'                                                                    │ │
│ │     mod_spec = ModuleSpec(name='__main__', loader=<zipimporter object                        │ │
│ │                "C:\Users\sunan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_… │ │
│ │                origin='C:\\Users\\sunan\\AppData\\Local\\Packages\\PythonSoftwareFoundation… │ │
│ │     pkg_name = ''                                                                            │ │
│ │  run_globals = {                                                                             │ │
│ │                │   '__name__': '__main__',                                                   │ │
│ │                │   '__doc__': None,                                                          │ │
│ │                │   '__package__': '',                                                        │ │
│ │                │   '__loader__': <zipimporter object                                         │ │
│ │                "C:\Users\sunan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_… │ │
│ │                │   '__spec__': ModuleSpec(name='__main__', loader=<zipimporter object        │ │
│ │                "C:\Users\sunan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_… │ │
│ │                origin='C:\\Users\\sunan\\AppData\\Local\\Packages\\PythonSoftwareFoundation… │ │
│ │                │   '__annotations__': {},                                                    │ │
│ │                │   '__builtins__': <module 'builtins' (built-in)>,                           │ │
│ │                │   '__file__':                                                               │ │
│ │                'C:\\Users\\sunan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python… │ │
│ │                │   '__cached__':                                                             │ │
│ │                'C:\\Users\\sunan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python… │ │
│ │                │   're': <module 're' from 'C:\\Program                                      │ │
│ │                Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qb… │ │
│ │                │   ... +2                                                                    │ │
│ │                }                                                                             │ │
│ │  script_name = None                                                                          │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│ C:\Users\sunan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCa │
│ che\local-packages\Python311\site-packages\click\core.py:1157 in __call__                        │
│                                                                                                  │
│ C:\Users\sunan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCa │
│ che\local-packages\Python311\site-packages\click\core.py:1078 in main                            │
│                                                                                                  │
│ C:\Users\sunan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCa │
│ che\local-packages\Python311\site-packages\click\core.py:1688 in invoke                          │
│                                                                                                  │
│ C:\Users\sunan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCa │
│ che\local-packages\Python311\site-packages\click\core.py:1434 in invoke                          │
│                                                                                                  │
│ C:\Users\sunan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCa │
│ che\local-packages\Python311\site-packages\click\core.py:783 in invoke                           │
│                                                                                                  │
│ C:\Users\sunan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCa │
│ che\local-packages\Python311\site-packages\animdl\core\cli\helpers\logger.py:79 in __inner__     │
│                                                                                                  │
│   76 │   │   │                                                                                   │
│   77 │   │   │   logging.setLoggerClass(SmartColouredLogger)                                     │
│   78 │   │   │                                                                                   │
│ ❱ 79 │   │   │   return f(*args, **kwargs, log_file=log_file, log_level=log_level)               │
│   80 │   │                                                                                       │
│   81 │   │   return __inner__                                                                    │
│   82                                                                                             │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │                args = ()                                                                     │ │
│ │ basic_config_kwargs = {                                                                      │ │
│ │                       │   'format': '[\x1b[35m%(filename)s:%(lineno)d\x1b[0m - %(asctime)s - │ │
│ │                       %(name)s: %(levelname)s] %(mes'+6,                                     │ │
│ │                       │   'level': 20                                                        │ │
│ │                       }                                                                      │ │
│ │                   f = <function banner_gift_wrapper.<locals>.wrapper.<locals>.__inner__ at   │ │
│ │                       0x00000221117AD800>                                                    │ │
│ │ file_logging_format = '[%(filename)s:%(lineno)d - %(asctime)s - %(name)s: %(levelname)s]     │ │
│ │                       %(message)s'                                                           │ │
│ │              kwargs = {                                                                      │ │
│ │                       │   'quality': 'best',                                                 │ │
│ │                       │   'range': <function RangeParameter.convert.<locals>.<lambda> at     │ │
│ │                       0x0000022111C00E00>,                                                   │ │
│ │                       │   'query': 'animepahe:NAruto',                                       │ │
│ │                       │   'special': '',                                                     │ │
│ │                       │   'idm': False,                                                      │ │
│ │                       │   'download_dir': '.',                                               │ │
│ │                       │   'index': None                                                      │ │
│ │                       }                                                                      │ │
│ │            log_file = None                                                                   │ │
│ │           log_level = 20                                                                     │ │
│ │      logging_format = '[\x1b[35m%(filename)s:%(lineno)d\x1b[0m - %(asctime)s - %(name)s:     │ │
│ │                       %(levelname)s] %(mes'+6                                                │ │
│ │ SmartColouredLogger = <class                                                                 │ │
│ │                       'animdl.core.cli.helpers.logger.setup_loggers.<locals>.wrapper.<local… │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\sunan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCa │
│ che\local-packages\Python311\site-packages\animdl\core\cli\helpers\banner.py:76 in __inner__     │
│                                                                                                  │
│   73 │   │   │   if log_level > 20:                                                              │
│   74 │   │   │   │   return f(*args, log_level=log_level, log_file=log_file, **kwargs)           │
│   75 │   │   │                                                                                   │
│ ❱ 76 │   │   │   return f(*args, log_level=log_level, log_file=log_file, **kwargs)               │
│   77 │   │                                                                                       │
│   78 │   │   return __inner__                                                                    │
│   79                                                                                             │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │      args = ()                                                                               │ │
│ │         f = <function animdl_download at 0x00000221117AD760>                                 │ │
│ │    kwargs = {                                                                                │ │
│ │             │   'quality': 'best',                                                           │ │
│ │             │   'range': <function RangeParameter.convert.<locals>.<lambda> at               │ │
│ │             0x0000022111C00E00>,                                                             │ │
│ │             │   'query': 'animepahe:NAruto',                                                 │ │
│ │             │   'special': '',                                                               │ │
│ │             │   'idm': False,                                                                │ │
│ │             │   'download_dir': '.',                                                         │ │
│ │             │   'index': None                                                                │ │
│ │             }                                                                                │ │
│ │  log_file = None                                                                             │ │
│ │ log_level = 20                                                                               │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\sunan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCa │
│ che\local-packages\Python311\site-packages\animdl\core\cli\commands\download.py:115 in           │
│ animdl_download                                                                                  │
│                                                                                                  │
│   112 │   │   │   │                                                                              │
│   113 │   │   │   │   expected_download_path = content_dir / content_title                       │
│   114 │   │   │   │                                                                              │
│ ❱ 115 │   │   │   │   status_enum, exception = helpers.safe_download_callback(                   │
│   116 │   │   │   │   │   session=http_client.client,                                            │
│   117 │   │   │   │   │   logger=logger,                                                         │
│   118 │   │   │   │   │   stream_urls=stream_urls,                                               │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │                      _ = 'animepahe'                                                         │ │
│ │                  anime = {                                                                   │ │
│ │                          │   'anime_url':                                                    │ │
│ │                          'https://animepahe.ru/anime/3772e658-cb4d-66f5-4991-089491453687',  │ │
│ │                          │   'name': 'Naruto'                                                │ │
│ │                          }                                                                   │ │
│ │                console = <console width=120 ColorSystem.TRUECOLOR>                           │ │
│ │            content_dir = WindowsPath('C:/Users/sunan/ANIME/Naruto')                          │ │
│ │           content_name = 'Naruto'                                                            │ │
│ │          content_title = 'E01'                                                               │ │
│ │                  count = 1                                                                   │ │
│ │           download_dir = '.'                                                                 │ │
│ │     download_directory = WindowsPath('C:/Users/sunan/ANIME')                                 │ │
│ │         episode_number = 1                                                                   │ │
│ │ expected_download_path = WindowsPath('C:/Users/sunan/ANIME/Naruto/E01')                      │ │
│ │                    idm = False                                                               │ │
│ │                  index = None                                                                │ │
│ │                 kwargs = {                                                                   │ │
│ │                          │   'log_file': None,                                               │ │
│ │                          │   'range': <function RangeParameter.convert.<locals>.<lambda> at  │ │
│ │                          0x0000022111C00E00>                                                 │ │
│ │                          }                                                                   │ │
│ │              log_level = 20                                                                  │ │
│ │                 logger = <SmartColouredLogger animepahe/downloader (INFO)>                   │ │
│ │                  match = <re.Match object; span=(0, 63),                                     │ │
│ │                          match='https://animepahe.ru/anime/3772e658-cb4d-66f5-499>           │ │
│ │               provider = 'animepahe'                                                         │ │
│ │        provider_module = <module 'animdl.core.codebase.providers.animepahe' from             │ │
│ │                          'C:\\Users\\sunan\\AppData\\Local\\Packages\\PythonSoftwareFoundat… │ │
│ │                quality = 'best'                                                              │ │
│ │                  query = 'animepahe:NAruto'                                                  │ │
│ │                      r = <function RangeParameter.convert.<locals>.<lambda> at               │ │
│ │                          0x0000022111C00E00>                                                 │ │
│ │                special = ''                                                                  │ │
│ │            stream_urls = <generator object ensure_extraction at 0x000002211178F880>          │ │
│ │     stream_urls_caller = functools.partial(<function fetcher.<locals>.<lambda> at            │ │
│ │                          0x0000022111C36520>, 1)                                             │ │
│ │                streams = [                                                                   │ │
│ │                          │   (                                                               │ │
│ │                          │   │   functools.partial(<function fetcher.<locals>.<lambda> at    │ │
│ │                          0x0000022111C36520>, 1),                                            │ │
│ │                          │   │   1                                                           │ │
│ │                          │   )                                                               │ │
│ │                          ]                                                                   │ │
│ │                  total = 1                                                                   │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\sunan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCa │
│ che\local-packages\Python311\site-packages\animdl\core\cli\helpers\__init__.py:81 in             │
│ safe_download_callback                                                                           │
│                                                                                                  │
│    78 │   log_level: "Optional[int]" = None,                                                     │
│    79 │   **kwargs,                                                                              │
│    80 ) -> "Tuple[SafeCaseEnum, Optional[BaseException]]":                                       │
│ ❱  81 │   flattened_streams = list(stream_urls)                                                  │
│    82 │                                                                                          │
│    83 │   try:                                                                                   │
│    84 │   │   streams = intelliq.filter_quality(flattened_streams, quality)                      │
│                                                                                                  │
│ ╭────────────────────────────────────────── locals ──────────────────────────────────────────╮   │
│ │        expected_download_path = WindowsPath('C:/Users/sunan/ANIME/Naruto/E01')             │   │
│ │                        kwargs = {}                                                         │   │
│ │                     log_level = 20                                                         │   │
│ │                        logger = <SmartColouredLogger animepahe/downloader (INFO)>          │   │
│ │                       quality = 'best'                                                     │   │
│ │                 retry_timeout = 0.3                                                        │   │
│ │                       session = <httpx.Client object at 0x0000022111469690>                │   │
│ │                   stream_urls = <generator object ensure_extraction at 0x000002211178F880> │   │
│ │ use_internet_download_manager = False                                                      │   │
│ ╰────────────────────────────────────────────────────────────────────────────────────────────╯   │
│                                                                                                  │
│ C:\Users\sunan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCa │
│ che\local-packages\Python311\site-packages\animdl\core\cli\helpers\__init__.py:55 in             │
│ ensure_extraction                                                                                │
│                                                                                                  │
│    52                                                                                            │
│    53                                                                                            │
│    54 def ensure_extraction(session, stream_uri_caller):                                         │
│ ❱  55 │   for stream in stream_uri_caller():                                                     │
│    56 │   │   if "further_extraction" in stream:                                                 │
│    57 │   │   │   yield from further_extraction(session, stream)                                 │
│    58 │   │   else:                                                                              │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │           session = <httpx.Client object at 0x0000022111469690>                              │ │
│ │ stream_uri_caller = functools.partial(<function fetcher.<locals>.<lambda> at                 │ │
│ │                     0x0000022111C36520>, 1)                                                  │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\sunan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCa │
│ che\local-packages\Python311\site-packages\animdl\core\codebase\providers\animepahe\__init__.py: │
│ 48 in iter_episode_streams                                                                       │
│                                                                                                  │
│   45 │   │   episode_number % per_page - 1                                                       │
│   46 │   ]                                                                                       │
│   47 │                                                                                           │
│ ❱ 48 │   yield from iter_stream_url_from_stream_session(                                         │
│   49 │   │   session, release_id, episode["session"]                                             │
│   50 │   )                                                                                       │
│   51                                                                                             │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │   current_page = 1                                                                           │ │
│ │        episode = {                                                                           │ │
│ │                  │   'id': 15779,                                                            │ │
│ │                  │   'anime_id': 1571,                                                       │ │
│ │                  │   'episode': 1,                                                           │ │
│ │                  │   'episode2': 0,                                                          │ │
│ │                  │   'edition': '',                                                          │ │
│ │                  │   'title': '',                                                            │ │
│ │                  │   'snapshot':                                                             │ │
│ │                  'https://i.animepahe.ru/snapshots/6693c23144b7f3d2bc73242740527ea77baa1d26… │ │
│ │                  │   'disc': 'BD',                                                           │ │
│ │                  │   'audio': 'jpn',                                                         │ │
│ │                  │   'duration': '00:23:20',                                                 │ │
│ │                  │   ... +3                                                                  │ │
│ │                  }                                                                           │ │
│ │ episode_number = 1                                                                           │ │
│ │       per_page = 30                                                                          │ │
│ │     release_id = '3772e658-cb4d-66f5-4991-089491453687'                                      │ │
│ │        session = <httpx.Client object at 0x0000022111469690>                                 │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\sunan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCa │
│ che\local-packages\Python311\site-packages\animdl\core\codebase\providers\animepahe\__init__.py: │
│ 37 in iter_stream_url_from_stream_session                                                        │
│                                                                                                  │
│   34 │   for url, resolution in STREAMS_REGEX.findall(stream_url_data.text):                     │
│   35 │   │   yield {                                                                             │
│   36 │   │   │   "quality": int(resolution),                                                     │
│ ❱ 37 │   │   │   "stream_url": get_animepahe_url(session, url),                                  │
│   38 │   │   }                                                                                   │
│   39                                                                                             │
│   40                                                                                             │
│                                                                                                  │
│ ╭─────────────────────────────────────── locals ───────────────────────────────────────╮         │
│ │      release_id = '3772e658-cb4d-66f5-4991-089491453687'                             │         │
│ │      resolution = '360'                                                              │         │
│ │         session = <httpx.Client object at 0x0000022111469690>                        │         │
│ │  stream_session = '6c49de67b1b45a908e5aff91b98f4972d8b91448311e63a28008ed331e66b28b' │         │
│ │ stream_url_data = <Response [200 OK]>                                                │         │
│ │             url = 'https://pahe.win/cvhun'                                           │         │
│ ╰──────────────────────────────────────────────────────────────────────────────────────╯         │
│                                                                                                  │
│ C:\Users\sunan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCa │
│ che\local-packages\Python311\site-packages\animdl\core\codebase\providers\animepahe\inner\__init │
│ __.py:53 in get_animepahe_url                                                                    │
│                                                                                                  │
│   50 │                                                                                           │
│   51 │   url = KWIK_REDIRECTION_RE.search(response.text).group(1)                                │
│   52 │                                                                                           │
│ ❱ 53 │   download_page = session.get(url)                                                        │
│   54 │                                                                                           │
│   55 │   full_key, key, v1, v2 = KWIK_PARAMS_RE.search(download_page.text).group(1, 2, 3, 4)     │
│   56                                                                                             │
│                                                                                                  │
│ ╭────────────────────────── locals ──────────────────────────╮                                   │
│ │ pahe_win_url = 'https://pahe.win/cvhun'                    │                                   │
│ │     response = <Response [200 OK]>                         │                                   │
│ │      session = <httpx.Client object at 0x0000022111469690> │                                   │
│ │          url = '#'                                         │                                   │
│ ╰────────────────────────────────────────────────────────────╯                                   │
│                                                                                                  │
│ C:\Users\sunan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCa │
│ che\local-packages\Python311\site-packages\httpx\_client.py:1045 in get                          │
│                                                                                                  │
│   1042 │   │                                                                                     │
│   1043 │   │   **Parameters**: See `httpx.request`.                                              │
│   1044 │   │   """                                                                               │
│ ❱ 1045 │   │   return self.request(                                                              │
│   1046 │   │   │   "GET",                                                                        │
│   1047 │   │   │   url,                                                                          │
│   1048 │   │   │   params=params,                                                                │
│                                                                                                  │
│ ╭───────────────────────────────────── locals ─────────────────────────────────────╮             │
│ │             auth = <httpx._client.UseClientDefault object at 0x0000022110950850> │             │
│ │          cookies = None                                                          │             │
│ │       extensions = None                                                          │             │
│ │ follow_redirects = <httpx._client.UseClientDefault object at 0x0000022110950850> │             │
│ │          headers = None                                                          │             │
│ │           params = None                                                          │             │
│ │             self = <httpx.Client object at 0x0000022111469690>                   │             │
│ │          timeout = <httpx._client.UseClientDefault object at 0x0000022110950850> │             │
│ │              url = '#'                                                           │             │
│ ╰──────────────────────────────────────────────────────────────────────────────────╯             │
│                                                                                                  │
│ C:\Users\sunan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCa │
│ che\local-packages\Python311\site-packages\httpx\_client.py:808 in request                       │
│                                                                                                  │
│    805 │   │   │   )                                                                             │
│    806 │   │   │   warnings.warn(message, DeprecationWarning)                                    │
│    807 │   │                                                                                     │
│ ❱  808 │   │   request = self.build_request(                                                     │
│    809 │   │   │   method=method,                                                                │
│    810 │   │   │   url=url,                                                                      │
│    811 │   │   │   content=content,                                                              │
│                                                                                                  │
│ ╭───────────────────────────────────── locals ─────────────────────────────────────╮             │
│ │             auth = <httpx._client.UseClientDefault object at 0x0000022110950850> │             │
│ │          content = None                                                          │             │
│ │          cookies = None                                                          │             │
│ │             data = None                                                          │             │
│ │       extensions = None                                                          │             │
│ │            files = None                                                          │             │
│ │ follow_redirects = <httpx._client.UseClientDefault object at 0x0000022110950850> │             │
│ │          headers = None                                                          │             │
│ │             json = None                                                          │             │
│ │           method = 'GET'                                                         │             │
│ │           params = None                                                          │             │
│ │             self = <httpx.Client object at 0x0000022111469690>                   │             │
│ │          timeout = <httpx._client.UseClientDefault object at 0x0000022110950850> │             │
│ │              url = '#'                                                           │             │
│ ╰──────────────────────────────────────────────────────────────────────────────────╯             │
│                                                                                                  │
│ C:\Users\sunan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCa │
│ che\local-packages\Python311\site-packages\httpx\_client.py:360 in build_request                 │
│                                                                                                  │
│    357 │   │   │   │   else Timeout(timeout)                                                     │
│    358 │   │   │   )                                                                             │
│    359 │   │   │   extensions = dict(**extensions, timeout=timeout.as_dict())                    │
│ ❱  360 │   │   return Request(                                                                   │
│    361 │   │   │   method,                                                                       │
│    362 │   │   │   url,                                                                          │
│    363 │   │   │   content=content,                                                              │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │    content = None                                                                            │ │
│ │    cookies = <Cookies[<Cookie __ddg2_=YW5pbWRsX3NheXNfaGkNCg. for .marin.moe />, <Cookie     │ │
│ │              XSRF-TOKEN=eyJpdiI6Ii9CajlJMkRXZGxXQk8zUVZxY25UNkE9PSIsInZhbHVlIjoiTHVyenlNeFE… │ │
│ │              for animepahe.ru />, <Cookie                                                    │ │
│ │              laravel_session=eyJpdiI6IlZnZGhpRlJSSWdqaEdzRjdOQis2aGc9PSIsInZhbHVlIjoiSHIxMF… │ │
│ │              for animepahe.ru />, <Cookie SERVERID=janna for animepahe.ru />, <Cookie        │ │
│ │              res=720 for animepahe.ru />, <Cookie aud=jpn for animepahe.ru />, <Cookie av1=0 │ │
│ │              for animepahe.ru />, <Cookie PHPSESSID=i1a2ppcec7i0hma008vg8hufh9 for pahe.win  │ │
│ │              />, <Cookie SERVERID=janna for pahe.win />]>                                    │ │
│ │       data = None                                                                            │ │
│ │ extensions = {'timeout': {'connect': 30, 'read': 30, 'write': 30, 'pool': 30}}               │ │
│ │      files = None                                                                            │ │
│ │    headers = Headers({'accept': '*/*', 'accept-encoding': 'gzip, deflate, br', 'connection': │ │
│ │              'keep-alive', 'user-agent': 'animdl/1.0.0'})                                    │ │
│ │       json = None                                                                            │ │
│ │     method = 'GET'                                                                           │ │
│ │     params = None                                                                            │ │
│ │       self = <httpx.Client object at 0x0000022111469690>                                     │ │
│ │    timeout = Timeout(timeout=30)                                                             │ │
│ │        url = URL('/')                                                                        │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\sunan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCa │
│ che\local-packages\Python311\site-packages\httpx\_models.py:335 in __init__                      │
│                                                                                                  │
│    332 │   │   self.extensions = {} if extensions is None else extensions                        │
│    333 │   │                                                                                     │
│    334 │   │   if cookies:                                                                       │
│ ❱  335 │   │   │   Cookies(cookies).set_cookie_header(self)                                      │
│    336 │   │                                                                                     │
│    337 │   │   if stream is None:                                                                │
│    338 │   │   │   content_type: typing.Optional[str] = self.headers.get("content-type")         │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │    content = None                                                                            │ │
│ │    cookies = <Cookies[<Cookie __ddg2_=YW5pbWRsX3NheXNfaGkNCg. for .marin.moe />, <Cookie     │ │
│ │              XSRF-TOKEN=eyJpdiI6Ii9CajlJMkRXZGxXQk8zUVZxY25UNkE9PSIsInZhbHVlIjoiTHVyenlNeFE… │ │
│ │              for animepahe.ru />, <Cookie                                                    │ │
│ │              laravel_session=eyJpdiI6IlZnZGhpRlJSSWdqaEdzRjdOQis2aGc9PSIsInZhbHVlIjoiSHIxMF… │ │
│ │              for animepahe.ru />, <Cookie SERVERID=janna for animepahe.ru />, <Cookie        │ │
│ │              res=720 for animepahe.ru />, <Cookie aud=jpn for animepahe.ru />, <Cookie av1=0 │ │
│ │              for animepahe.ru />, <Cookie PHPSESSID=i1a2ppcec7i0hma008vg8hufh9 for pahe.win  │ │
│ │              />, <Cookie SERVERID=janna for pahe.win />]>                                    │ │
│ │       data = None                                                                            │ │
│ │ extensions = {'timeout': {'connect': 30, 'read': 30, 'write': 30, 'pool': 30}}               │ │
│ │      files = None                                                                            │ │
│ │    headers = Headers({'accept': '*/*', 'accept-encoding': 'gzip, deflate, br', 'connection': │ │
│ │              'keep-alive', 'user-agent': 'animdl/1.0.0'})                                    │ │
│ │       json = None                                                                            │ │
│ │     method = 'GET'                                                                           │ │
│ │     params = None                                                                            │ │
│ │       self = <Request('GET', '/')>                                                           │ │
│ │     stream = None                                                                            │ │
│ │        url = URL('/')                                                                        │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\sunan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCa │
│ che\local-packages\Python311\site-packages\httpx\_models.py:1044 in set_cookie_header            │
│                                                                                                  │
│   1041 │   │   """                                                                               │
│   1042 │   │   Sets an appropriate 'Cookie:' HTTP header on the `Request`.                       │
│   1043 │   │   """                                                                               │
│ ❱ 1044 │   │   urllib_request = self._CookieCompatRequest(request)                               │
│   1045 │   │   self.jar.add_cookie_header(urllib_request)                                        │
│   1046 │                                                                                         │
│   1047 │   def set(self, name: str, value: str, domain: str = "", path: str = "/") -> None:      │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ request = <Request('GET', '/')>                                                              │ │
│ │    self = <Cookies[<Cookie __ddg2_=YW5pbWRsX3NheXNfaGkNCg. for .marin.moe />, <Cookie        │ │
│ │           XSRF-TOKEN=eyJpdiI6Ii9CajlJMkRXZGxXQk8zUVZxY25UNkE9PSIsInZhbHVlIjoiTHVyenlNeFE4OT… │ │
│ │           for animepahe.ru />, <Cookie                                                       │ │
│ │           laravel_session=eyJpdiI6IlZnZGhpRlJSSWdqaEdzRjdOQis2aGc9PSIsInZhbHVlIjoiSHIxMFIvV… │ │
│ │           for animepahe.ru />, <Cookie SERVERID=janna for animepahe.ru />, <Cookie res=720   │ │
│ │           for animepahe.ru />, <Cookie aud=jpn for animepahe.ru />, <Cookie av1=0 for        │ │
│ │           animepahe.ru />, <Cookie PHPSESSID=i1a2ppcec7i0hma008vg8hufh9 for pahe.win />,     │ │
│ │           <Cookie SERVERID=janna for pahe.win />]>                                           │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\sunan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCa │
│ che\local-packages\Python311\site-packages\httpx\_models.py:1182 in __init__                     │
│                                                                                                  │
│   1179 │   │   """                                                                               │
│   1180 │   │                                                                                     │
│   1181 │   │   def __init__(self, request: Request) -> None:                                     │
│ ❱ 1182 │   │   │   super().__init__(                                                             │
│   1183 │   │   │   │   url=str(request.url),                                                     │
│   1184 │   │   │   │   headers=dict(request.headers),                                            │
│   1185 │   │   │   │   method=request.method,                                                    │
│                                                                                                  │
│ ╭────────────────────────────────────── locals ───────────────────────────────────────╮          │
│ │ request = <Request('GET', '/')>                                                     │          │
│ │    self = <httpx._models.Cookies._CookieCompatRequest object at 0x00000221117EB710> │          │
│ ╰─────────────────────────────────────────────────────────────────────────────────────╯          │
│                                                                                                  │
│ C:\Program                                                                                       │
│ Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\urllib │
│ \request.py:322 in __init__                                                                      │
│                                                                                                  │
│    319 │   def __init__(self, url, data=None, headers={},                                        │
│    320 │   │   │   │    origin_req_host=None, unverifiable=False,                                │
│    321 │   │   │   │    method=None):                                                            │
│ ❱  322 │   │   self.full_url = url                                                               │
│    323 │   │   self.headers = {}                                                                 │
│    324 │   │   self.unredirected_hdrs = {}                                                       │
│    325 │   │   self._data = None                                                                 │
│                                                                                                  │
│ ╭────────────────────────────────────────── locals ───────────────────────────────────────────╮  │
│ │            data = None                                                                      │  │
│ │         headers = {                                                                         │  │
│ │                   │   'accept': '*/*',                                                      │  │
│ │                   │   'accept-encoding': 'gzip, deflate, br',                               │  │
│ │                   │   'connection': 'keep-alive',                                           │  │
│ │                   │   'user-agent': 'animdl/1.0.0'                                          │  │
│ │                   }                                                                         │  │
│ │          method = 'GET'                                                                     │  │
│ │ origin_req_host = None                                                                      │  │
│ │            self = <httpx._models.Cookies._CookieCompatRequest object at 0x00000221117EB710> │  │
│ │    unverifiable = False                                                                     │  │
│ │             url = '/'                                                                       │  │
│ ╰─────────────────────────────────────────────────────────────────────────────────────────────╯  │
│                                                                                                  │
│ C:\Program                                                                                       │
│ Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\urllib │
│ \request.py:348 in full_url                                                                      │
│                                                                                                  │
│    345 │   │   # unwrap('<URL:type://host/path>') --> 'type://host/path'                         │
│    346 │   │   self._full_url = unwrap(url)                                                      │
│    347 │   │   self._full_url, self.fragment = _splittag(self._full_url)                         │
│ ❱  348 │   │   self._parse()                                                                     │
│    349 │                                                                                         │
│    350 │   @full_url.deleter                                                                     │
│    351 │   def full_url(self):                                                                   │
│                                                                                                  │
│ ╭───────────────────────────────────── locals ─────────────────────────────────────╮             │
│ │ self = <httpx._models.Cookies._CookieCompatRequest object at 0x00000221117EB710> │             │
│ │  url = '/'                                                                       │             │
│ ╰──────────────────────────────────────────────────────────────────────────────────╯             │
│                                                                                                  │
│ C:\Program                                                                                       │
│ Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\urllib │
│ \request.py:377 in _parse                                                                        │
│                                                                                                  │
│    374 │   def _parse(self):                                                                     │
│    375 │   │   self.type, rest = _splittype(self._full_url)                                      │
│    376 │   │   if self.type is None:                                                             │
│ ❱  377 │   │   │   raise ValueError("unknown url type: %r" % self.full_url)                      │
│    378 │   │   self.host, self.selector = _splithost(rest)                                       │
│    379 │   │   if self.host:                                                                     │
│    380 │   │   │   self.host = unquote(self.host)                                                │
│                                                                                                  │
│ ╭───────────────────────────────────── locals ─────────────────────────────────────╮             │
│ │ rest = '/'                                                                       │             │
│ │ self = <httpx._models.Cookies._CookieCompatRequest object at 0x00000221117EB710> │             │
│ ╰──────────────────────────────────────────────────────────────────────────────────╯             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: unknown url type: '/'

C:\Users\sunan\ANIME>

**Comment by Vacreio** [comment]
Also I cannot find "Config.json"

**Comment by Incredibleflamer** [comment]
delete your current code and install the fresh one by :

![image](https://github.com/Incredibleflamer/anime-batch-downloader/assets/84078595/47045f4e-2d8d-4de7-bf36-0526f5b9b9d7)

Download zip and extract the files then edit the config.json by refering https://github.com/Incredibleflamer/anime-batch-downloader

**Comment by TheYogMehta** [comment]
@Vacreio  i have re worked on this downloader and update it to latest version also it doesnt works on python anymore sorry about that , you need to have node js in your machine 
Link to node js : https://nodejs.org/en

one more thing its a bit fast then the old versions
